# define the services/containers to be run
services:

  frontend:

    depends_on:
      - backend

    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 5173


    networks:
      - app-network

  # define the api service/container
  backend:
    # api service depends on the db service so the db service will be started before the api service
    depends_on:
      - db

    # specify the build context for the api service
    build: 
     context: ./backend
     dockerfile: Dockerfile
    expose:
      - 8000

    env_file:
       - ./backend/.env

    volumes:
      - ./backend:/app

    networks:
      - app-network

  db:

    image: postgres:13


    env_file:
      - ./backend/.env

    ports:
      - 5432:5432


    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest

    ports:
      - 80:80
      - 8090:81  # Nginx Proxy Manager admin interface
      - 443:443

    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt
    networks:
      - app-network

# define the volumes to be used by the services
volumes:
  postgres_data:
  nginx_proxy_manager_data:
  nginx_proxy_manager_letsencrypt:

networks:
  app-network:
    driver: bridge
