# version: '3.8'

# services:
#   app:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: app 
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: app  
#     #volumes:
#     #  - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped
#     ports:
#       - "5432:5432"

#   adminer:
#     image: adminer
#     restart: unless-stopped
#     ports:
#       - "8080:8080"
#     depends_on:
#       - app

# #volumes:
# #  postgres_data: {}



version: '3.8'

services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://app:password@postgres:5432/app
    ports:
      - "65069:65069"
    depends_on:
      - postgres 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
