name: Deploy Docker Compose to VM

on:
  push:
    branches:
      - deploy # or any branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd devops-stage-2/docker-compose.yml
            docker-compose down
            docker-compose pull
            docker-compose up -d
